export type PokemonTypeToSvgType = Record<string, string>;
export const PokemonTypeToSvg: PokemonTypeToSvgType = {
  bug: "/pokemon-type-icons/bug.svg",
  dark: "/pokemon-type-icons/dark.svg",
  dragon: "/pokemon-type-icons/dragon.svg",
  electric: "/pokemon-type-icons/electric.svg",
  fairy: "/pokemon-type-icons/fairy.svg",
  fighting: "/pokemon-type-icons/fighting.svg",
  fire: "/pokemon-type-icons/fire.svg",
  flying: "/pokemon-type-icons/flying.svg",
  ghost: "/pokemon-type-icons/ghost.svg",
  grass: "/pokemon-type-icons/grass.svg",
  ground: "/pokemon-type-icons/ground.svg",
  ice: "/pokemon-type-icons/ice.svg",
  normal: "/pokemon-type-icons/normal.svg",
  poison: "/pokemon-type-icons/poison.svg",
  psychic: "/pokemon-type-icons/psychic.svg",
  rock: "/pokemon-type-icons/rock.svg",
  steel: "/pokemon-type-icons/steel.svg",
  water: "/pokemon-type-icons/water.svg",
};

export type PokemonTypeToTailwindColorType = Record<string, string>;
export const PokemonTypeToTailwindColor: PokemonTypeToTailwindColorType = {
  bug: "bg-lime-500",
  dark: "bg-gray-800",
  dragon: "bg-indigo-700",
  electric: "bg-yellow-400",
  fairy: "bg-pink-300",
  fighting: "bg-red-600",
  fire: "bg-orange-500",
  flying: "bg-blue-300",
  ghost: "bg-purple-700",
  grass: "bg-green-500",
  ground: "bg-yellow-700",
  ice: "bg-cyan-300",
  normal: "bg-gray-400",
  poison: "bg-purple-500",
  psychic: "bg-pink-500",
  rock: "bg-yellow-600",
  steel: "bg-gray-500",
  water: "bg-blue-500",
};

export type PokemonTypeToKorType = Record<string, string>;
export const PokemonTypeToKor: PokemonTypeToKorType = {
  bug: "벌레",
  dark: "악",
  dragon: "드래곤",
  electric: "전기",
  fairy: "페어리",
  fighting: "격투",
  fire: "불꽃",
  flying: "비행",
  ghost: "고스트",
  grass: "풀",
  ground: "땅",
  ice: "얼음",
  normal: "노말",
  poison: "독",
  psychic: "에스퍼",
  rock: "바위",
  steel: "강철",
  water: "물",
};
